### ISSUE TITLE
【禁止刷星❌】关于本项目近期Star数异常增长的警告

### ISSUE THREAD

**Issue by starlose** [caoergou/cnpip#1]
@caoergou 您好，

最近我们注意到您的项目 cnpip 的 GitHub Star 数量在短时间内出现了异常增长。然而，通过对这些新 Star 账号的深入调查，我们发现其中大部分都是僵尸机器人账号，这些账号的内容都是垃圾填充，明显存在虚假刷 Star 的行为。

GitHub 是一个开发者们分享和交流技术的社区，刷 Star 的行为不仅违反了社区准则，也破坏了社区的公平性。作为一个资深开发者，我们感到非常失望和愤怒。虚假的 Star 不仅误导了其他开发者，也严重影响了真正优秀项目的曝光和推广。

中国的开发者在 GitHub 刷 Star 的现象已经引起了国际开源社区广泛的不满，我们不能让这种不良风气蔓延。希望您能够立即停止这种行为，并对社区和其他开发者进行道歉。如果此行为继续，我们将继续向 GitHub 官方举报并追踪处理情况。

GitHub 社区需要的是诚信和透明，大家都希望通过公平的竞争来获得认可。开源靠的是真实价值，而不是数据造假。希望您能重视这个问题，能以实际行动维护社区的公正，共同营造一个健康的技术交流环境。

开源不易，且行且珍惜。共勉！

一位热爱 GitHub 社区的开发者

**Comment by starlose** [comment]
恭喜💐 已经由耻辱榜收录并通知各个科技媒体——
https://github.com/starfaking/cnpip

**Comment by caoergou** [comment]
本身这个项目也是为了方便国人在使用Python安装镜像包时能够更方便点，带自娱自乐性质写的一个小项目，然后刷点数据装饰下，图个乐罢了。如果认为什么影响社区准则什么的，那在这里说一个抱歉，不过我也没办法去除这些刷的Star。

不过你的这个行为也挺有意思的，大概看了下发现似乎是手动进行的。
<img width="462" alt="image" src="https://github.com/user-attachments/assets/49afc47b-0d3f-4c31-b6da-886627029ad5">
而且自己写的comment自己给自己点赞也挺好玩的哈哈哈哈
但是手动做这事，同时自己给自己点赞，不也就相当于自娱自乐吗？
如果你有兴趣成立个专门这种做的账号，利用 GitHub Actions 自动化进行 Star 真假的检测，讲真，我有兴趣加入，可以与我联系。

**Comment by starlose** [comment]
@caoergou 请不要逃避这个问题，你当然可以取消这些 Star，你只需要把这些僵尸依次 block 即可，无论是否是你主动购买的。

![image](https://github.com/user-attachments/assets/07e9400a-7204-4e24-b40a-db10aab3bae3)

![image](https://github.com/user-attachments/assets/46b93785-04be-48dc-9ea0-c96d09476ae7)
