### ISSUE TITLE
修改的是~/.pip/pip.conf 优先读取的是~/.config/pip/pip.conf 

### ISSUE THREAD

**Issue by zibingo** [caoergou/cnpip#2]

**Comment by caoergou** [comment]
收到，明天我详细下。
顺便问下，你是啥系统？

**Comment by zibingo** [comment]
> 收到，明天我详细下。 顺便问下，你是啥系统？

ubuntu 22.04

**Comment by caoergou** [comment]
https://github.com/caoergou/cnpip/releases/tag/v1.2.0


新发布了1.2.0，修改了切镜像源的方式，可以试试
