### ISSUE TITLE
add westlake mirror

### ISSUE THREAD

**Issue by andrewfowlie** [caoergou/cnpip#4]
Great app!

https://mirrors.westlake.edu.cn/pypi/simple/

Could this mirror be added?

**Comment by caoergou** [comment]
Sure, why don't you submit a PR? 
Because all the mirror sources are defined in the file [mirrors.py](https://github.com/caoergou/cnpip/blob/main/cnpip/mirrors.py), it's easy to modify them
and you're welcome to be the app's contributors!
